import { ReactNode } from "react";
import { Metadata } from "next";
import Logout from "@/components/Logout";
import AdminHeader from "@/components/Admin/AdminHeader/page";

// export const metadata: Metadata = {
//   title: "user-admin-public",
//   description: "Generated by create-next-app",
// };

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <div className="min-h-screen bg-gray-100">
      {/* <Logout /> */}
      <AdminHeader />
      <main className="p-6">{children}</main>
    </div>
  );
};

export default Layout;
