import { ReactNode } from "react";
import Header from "@/components/user/Header";
import Footer from "@/components/user/Footer";

// export const metadata: Metadata = {
//   title: "user-admin-public",
//   description: "Generated by create-next-app",
// };

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <div>
      <Header />
      <div className="w-full min-h-[calc(100vh-133px)]">{children}</div>
      <Footer />
    </div>
  );
};

export default Layout;
